name: build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build gettext cmake curl build-essential

    - name: Build
      run: |
        make CMAKE_BUILD_TYPE=Release
        mkdir -p my-nvim
        make install DESTDIR=$(pwd)/my-nvim

    - name: Uploat artifact
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: my-nvim
